language: go
go:
  - "1.13"
sudo: false
before_install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.22.2
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
install:
  - $(go env GOPATH)/bin/golangci-lint --version
script:
  - $(go env GOPATH)/bin/golangci-lint run ./...
  - go build ./...
  - go test ./... --short
