language: go
go:
  - "1.14"
sudo: false

before_install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.31.0

install:
  - golangci-lint --version

script:
  - golangci-lint run ./...
  - go build ./...
  - go test ./... --short

  # V2
  - cd v2
  - golangci-lint run ./...
  - go build ./...
  - go test ./... --short
