[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.0.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.12.2"

[[constraint]]
  name = "github.com/lonnblad/opencensus-go-exporter-datadog"
  branch = "feature/oc-error-tag"

[prune]
  go-tests = true
  unused-packages = true
