# Reference of settings:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

# To remedy '<file>: File is not `goimports`-ed (goimports)' do:
# goimports -w -local github.com/SKF <file>

# all available settings of specific linters
linters-settings:
  errcheck:
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/SKF/go-utility/v2
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10
  gocognit:
    min-complexity: 20
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100

issues:
  # List of regexps of issue texts to exclude, empty list by default.
  # To see excluded by default patterns execute `golangci-lint run --help`
  exclude:

linters:
  enable-all: true
  disable:
    - depguard
    - gochecknoinits
    - gochecknoglobals
    - lll
